"""empty message

Revision ID: eade2d91c679
Revises: e28ac34acf9d
Create Date: 2020-05-24 12:28:27.640440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eade2d91c679'
down_revision = 'e28ac34acf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('subtitle', sa.String(length=64), nullable=True),
    sa.Column('imageUrl', sa.String(length=64), nullable=True),
    sa.Column('fields', sa.String(length=1024), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('output', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=64), nullable=True),
    sa.Column('calcmethod', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_name'), 'form', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_name'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
